name: 🔄 Auto Sync Fork from Upstream

on:
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 2 AM UTC
  workflow_dispatch:       # Allows manual triggering from GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

    - name: Add upstream remote and fetch
        run: |
          git remote | grep upstream || git remote add upstream https://github.com/LunaTechLab/MoonTV.git
          git fetch upstream

      - name: Merge upstream/main into fork/main
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "Auto-sync: Merged upstream changes"
          git push origin main
