name: 🔄 Auto Sync Fork from Upstream

on:
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 2 AM UTC
  workflow_dispatch:      # Manual run option

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # We will handle auth manually

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/LunaTechLab/MoonTV.git
          git fetch upstream

      - name: Merge upstream/main into fork/main
        run: |
          git checkout main  # Change to 'master' if needed
          git merge upstream/main --allow-unrelated-histories -m "Auto-sync: Merge upstream"

      - name: Push changes back to fork
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git push origin main  # Change to 'master' if needed

